config/routes.rb
Rails.application.routes.draw do
  
  resources :news, only: [ :index, :show ]
  
  devise_for :users, controllers: { registrations: 'users/registrations' } 
  root 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users, path: '', only: [ :index ]
    resources :users, except: [ :index, :new ]
    resources :news
  end
  
  resources :users, only: [ :update ]
  get '/profile', to: 'users#edit', via: 'get', :as => :profile
  
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable;
  has_many :news;

  enum digest: [ :nodigest, :weekly, :dayly  ]
  before_save { self.email = email.downcase } # :default_values
  before_create :default_values
  validates :name, presence: true, length: { maximum: 255 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  
  def default_values
    self.digest ||= :weekly;
    self.digest = :weekly if self.digest.nil?
  end
  
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #before_action :denied_access, only: [:create]
  #before_action :check_permissions
  
  
  def denied_access
    format.html { render :file => "#{Rails.root}/public/forbid.html", :layout => false, :status => :ok }
    
  end
  
  def check_permissions
  
    unless (user_signed_in? && current_user.admin?) then
      
      #render json: {error: "Вы не имеете прав для доступа к данному разделу " << (user_signed_in? ? "true" : "false")}
      #return false
      respond_to do |format|
        format.html { render :file => "#{Rails.root}/public/forbid.html", :layout => false, :status => :ok }
      #  format.html { redirect_to root_path, notice: "Вы не имеете прав для доступа к разделу admin " << (user_signed_in? ? "true" : "false") }
      end
    end
    return true
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success] = t('.success')
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    my_logger ||= Logger.new("#{Rails.root}/log/my.log")
    my_logger.info "USER HANDLER" 
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = t('.success')
        format.html { redirect_to action: 'edit', id: @user.id, status: :see_other}
        format.json { render :show, status: :see_other, location: @user }
      else
        format.html { render action: 'edit', id: @user.id, status: :see_other}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      flash[:success] = t('.success')
      format.html { redirect_to action: 'index' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :admin, :editor, :digest)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :name, :digest])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]
  before_action :set_profile_user, only: [:update, :edit]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    user_params.user_id = current_user.id
    
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success] = t('.success')
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = t('.success')
        format.html { redirect_to profile_path}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      flash[:success] = t('.success')
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    
    def set_profile_user
      unless (user_signed_in?) then
        respond_to do |format|
          format.html { render :file => "#{Rails.root}/public/forbid.html", :layout => false, :status => :ok }
        end
      end
      @user = current_user
      return true
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
       params.require(:user).permit(:name, :digest)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.slim
.row
  .col-md-6.col-md-offset-3
    = form_with(model: @user, url: url_for({controller: 'admin/users', action: :show, id: params[:id]}), local: true) do |form|
      = render 'shared/error_messages'
      = form.label :email
      = form.text_field :email, class: 'form-control'
      = form.label t("field_user_name")
      = form.text_field :name, class: 'form-control'
      .form-check
        = form.check_box :admin, class: 'form-check-input'
        = form.label t("field_user_admin"), class: 'form-check-label'
      .form-check
        = form.check_box :editor, class: 'form-check-input', id: 'editor_checkbox'
        = form.label t("field_user_editor"), class: 'form-check-label', for: 'editor_checkbox'
      = form.label t("field_user_digest")
      = form.select(:digest, User.digests.keys.map {|digest| [t(digest),digest]} , {}, class: 'form-control')
      = form.submit t(".save_button"), class: "btn btn-primary"

app/views/admin/users/edit.html.slim
h1
  | Редактирование пользователя
= render 'form', user: @user
= link_to '<< Список пользователей', controller: :users, action: :index

app/views/admin/users/index.html.slim
h1
  | Пользователи
table.table
  thead
    tr
      th
        | ID
      th
        | Имя
      th
        | email
      th
        | редактор
      th
        | админ
      th
        | Дайджест
      th[colspan="4"]
  tbody
    - @users.each do |user|
      tr
        td
          = user.id
        td
          = user.name
        td
          = user.email
        td
          = user.editor ? "да" : "нет"
        td
          = user.admin ? "да" : "нет"
        td
          = user.digest
        td
          = link_to "Просмотр", :controller => :users, :action => :show, :id => user.id
        td
          = link_to "Редактировать", :controller => :users, :action => :edit, :id => user.id
        td
          = link_to 'Удалить', {controller: :users, action: :show, id: user.id}, method: :delete, data: { confirm: 'Вы уверены?' }
br

app/views/admin/users/new.html.slim
h1
  | New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/admin/users/show.html.slim
h1
  =t(".title", user_name: @user.email)
p
  strong
    | Email:
  = @user.email
p
  strong
    =t("field_user_name")
    | :
  = @user.name
p
  strong
    =t("field_user_admin")
    | :
  = @user.admin
p
  strong
    =t("field_user_editor")
    | :
  = @user.editor
p
  strong
    =t("field_user_digest")
    | :
  = t(@user.digest)
= link_to t(".edit_link"), url_for({controller: 'admin/users', action: :edit, id: @user.id})
|  | 
= link_to t(".index_link"), admin_users_path