config/routes.rb
Rails.application.routes.draw do
  
  resources :news, only: [ :index, :show ]
  
  devise_for :users, controllers: { registrations: 'users/registrations' } 
  root 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users, path: '', only: [ :index ]
    resources :users, except: [ :index, :new ]
    resources :news
  end
  
  resources :users, only: [ :update ]
  get '/profile', to: 'users#edit', via: 'get', :as => :profile
  
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    = t('.fio')
  nav
    ul
      li
        = link_to t('.news_page'),   '#'

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "test2 app", root_path, id: "logo"
    nav
      ul.nav.navbar-nav.navbar-right
        li
          = link_to t('.main_page'), root_path
        li
          = link_to t('.news_page'), news_index_path
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              = t('.account')
              b.caret
            ul.dropdown-menu
              li
                = link_to t('.profile_page'), profile_path
              - if current_user.editor?
                li
                  = link_to t('.news_page'), controller: 'admin/news', action: :index
              - if current_user.admin?
                li
                  = link_to t('.users_page'), controller: 'admin/users', action: :index
              li.divider
              li
                = link_to t('.logout'), destroy_user_session_path, :method => :delete
        - else
          li
            = link_to t('.login'), new_user_session_path
          li
            = link_to t('.register'), new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Test2App
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        |  <div class="alert alert-
        = message_class_bottstrap_from_devise(message_type)
        | ">
        = message
        | </div>
      
      = yield
      = render 'layouts/footer'